myvenv2023/GToProject/src/account/urls.py
from django.urls import path

from account.views import (home_View,Signup,
                           Login,logout_View,
                           Signup_Free_Account_User,
                           Signup_Custome_Account_User,
                           json_View,
                           signupoption_View,
                           profile_View,
                           edit_account_view)
from django.conf import settings
app_name="account"
urlpatterns = [
   path('',home_View, name='home'),
   path('json',json_View,name='json'),
   path('signup', Signup.as_view(), name='signup'),
   path('signupoption',signupoption_View,name='signupoption'),
   path('login', Login.as_view(), name='login'),
   path('logout',logout_View,name='logout'),
   path('free_account',Signup_Free_Account_User.as_view(),name='free_account'),
   path('custome_account',Signup_Custome_Account_User.as_view(),name='custome_account'),
   path('profile',profile_View,name='profile'),
   path('edit',edit_account_view,name='edit'),
]

myvenv2023/GToProject/src/mainapp/urls.py
from django.urls import path


from mainapp.views import (
   search_View,graph_Shaw_View,graph_Shaw_View_Index
)

app_name="mainapp"
urlpatterns = [
  
   path('search', search_View, name='search'),
   path('graph',graph_Shaw_View,name='graph'),
   path('index',graph_Shaw_View_Index,name='index'),
   
]

myvenv2023/GToProject/src/projectWinner/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static

from django.conf import settings
from django.contrib.auth import views as auth_views
from django.contrib.auth.views import LoginView,LogoutView
urlpatterns = [
    path("",include("account.urls")),
    path("admin/", admin.site.urls),
    path("mainapp",include("mainapp.urls")),
     # Password reset links (ref: https://github.com/django/django/blob/master/django/contrib/auth/views.py)
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='password_reset/password_change_done.html'), 
        name='password_change_done'),
    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='password_reset/password_change.html'), 
        name='password_change'),
    path('password_reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='password_reset/password_reset_done.html'),
     name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='password_reset/password_reset_confirm.html'), name='password_reset_confirm'),
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name='password_reset/password_reset_form.html'), name='password_reset'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='password_reset/password_reset_complete.html'),
     name='password_reset_complete'),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myvenv2023/GToProject/src/templates/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta http-equiv="refresh" content="36000">

    <title>Hambaricho Eco-Toursim Site</title>
    <meta content="" name="description">
    <meta content="" name="keywords">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta rel="search" type="application/opensearchdescription+xml" href="/open_search.xml" title="Hambaricho.org">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="i18nDefaultLocale" content="en_US">
    <meta name="i18nLocale" content="en_US">
    <meta name="application-name" content="Hambaricho Toursim">
    <meta name="application-url" content="https://hambaricho.org">
    <meta name="google" content="notranslate">
    <meta content="" name="description">
    <meta content="" name="keywords">

    <!-- Favicons -->
    <link href="{% static 'assets/img/hambimg/ham1.jpg'%}" rel="icon">
    <link href="{% static 'assets/img/hambimg/ham1.jpg'%}" rel="apple-touch-icon">

      <!-- Croppercss -->
      <link rel="stylesheet" href="{% static 'assets/cropperjs/dist/cropper.min.css' %}">

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Roboto:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

    <!-- Vendor CSS Files -->
   <!-- <link href="assets/vendor/fontawesome-free/css/all.min.css'%}" rel="stylesheet">-->
    <link href="{% static 'assets/vendor/animate.css/animate.min.css'%}" rel="stylesheet">
    <link href="{% static 'assets/vendor/aos/aos.css'%}" rel="stylesheet">
    <link href="{% static 'assets/vendor/bootstrap/css/bootstrap.min.css'%}" rel="stylesheet">
    <link href="{% static 'assets/vendor/bootstrap-icons/bootstrap-icons.css'%}" rel="stylesheet">
    <link href="{% static 'assets/vendor/boxicons/css/boxicons.min.css'%}" rel="stylesheet">
    <link href="{% static 'assets/vendor/glightbox/css/glightbox.min.css'%}" rel="stylesheet">
    <link href="{% static 'assets/vendor/swiper/swiper-bundle.min.css'%}" rel="stylesheet">

    <!-- Template Main CSS File -->
    <link href="{% static 'assets/css/style.css'%}" rel="stylesheet">


    <!-- =======================================================
  * Template Name: Hambricho - v1.0.0
  
  
  * Author: kibru.com
  * License: https://Hambrcho.com/license/
  ======================================================== -->
  <!-- Cropperjs css-->
  <link rel="stylesheet" href="{% static 'cropperjs/dist/cropper.min.css' %}">
  <!--on loader-->
  <script>hljs.initHighlightingOnLoad();</script>
</head>

<body>

    <!-- ======= Top Bar ======= -->
    
    <div id="topbar" class="d-flex align-items-center fixed-top">
        <div class="container d-flex align-items-center justify-content-center justify-content-md-between">
            <div class="align-items-center d-none d-md-flex">
                <i class="bi bi-clock"></i> Monday - Sunday 
            </div>
            <div class="align-items-center d-none d-md-flex">
                            {% if messages %}
                <ul class="messages" style="color:red">
                    {% for message in messages %}
                    <li
                    {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                    {% endfor %}
                </ul>
                {% endif %}
            </div>
            <div class="d-flex align-items-center">
                <i class="bi bi-phone"></i> Call us now +251 5589 554886
            </div>
        </div>
    </div>

    <!-- ======= Header ======= -->
    <header id="header" class="fixed-top">
        <div class="container d-flex align-items-center">

            <a href="{% url 'account:home'%}" class="logo me-auto">
                
                <img src="{% static 'assets/img/Logo/logo.jpg' %}" alt="" class="img-fluid">
                
            </a>
           

            <nav id="navbar" class="navbar order-last order-lg-0">
                <ul>
                  
                  
                    {% if user.is_authenticated %}
                   
                   
                <li><a class="nav-link scrollto" href="{% url 'account:profile'%}">Profile</a></li>
                {% if  user.is_superuser%}
                <li><a class="nav-link scrollto" href="{% url 'admin:index'%}">Dashboard </a></li>
                {%endif%}
               
                
                   
                   

              
               
                <li><a class="nav-link scrollto" href="{% url 'account:logout'%}"><button type="button" class="login-btn">Logout </button></a></li>
                    
                    {% else %} 

                    {% block link%}

                    {% endblock%}

                    
                    
                    {% endif%}
                    
                </ul>
                <i class="bi bi-list mobile-nav-toggle"></i>
            </nav>
            <!-- .navbar -->


        </div>
    </header>
    <!-- End Header -->
    <!--Loader-->
    <div class="container" id="id_loading_spinner" style="display: none">
        <div class="d-flex flex-row mx-auto flex-grow-1 justify-content-center">
            <div class="spinner-border text-primary" role="status">
                <span class="sr-only">Loading...</span>
            </div>
        </div>
    </div>

  

    <main id="main">


        <div class=' container'> 
            <div class=' row'> 
                <div class='mt-5'>  
                    <div class='mt-5'>   </div>     
                </div> 
                
            </div>  
        </div>

       
      


      {% block  content  %}
      {% endblock  %}



    </main>
    <!-- End #main -->

    <!-- ======= Footer ======= -->
  
   
    <div class="text-light bg-dark col-lg-12 col-sm-12 justify-content-center justify-item-center"  id="copyright">
           
        <div class="row bg-dark col-lg-12 col-sm-12">
                <div class="copyright float-start col-lg-6 col-sm-6 mt-4 mb-4  text-center ">
                    &copy; Copyright
                    {% for footers in footer%} 
                    {{footers.copyright|date:"Y"}} 
                    {% endfor%}
                
                    <strong><span> 
                        {% for footers in footer %}
                        {{footers.our_domian_name}} 
                    {% endfor%}
                
                    </span></strong>. All Rights Reserved
                </div>
       
                <div class="credits float-end col-lg-6 col-sm-6 mt-4 mb-4 text-center">

                    Designed and Developed by <a href="https://kibrut.netlify.app/">BrightTeamAfricaTech PLC</a>
                </div>
        </div>
       
</div>
    
    <!-- End Footer -->
    <!--spinner Loader--> 

    <div id="preloader"></div>
    <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>
    <!--End spinner Loader--> 

    <!-- Vendor JS Files -->
    <script src="{% static 'assets/vendor/purecounter/purecounter.js'%}"></script>
    <script src="{% static 'assets/vendor/aos/aos.js'%}"></script>
    <script src="{% static 'assets/vendor/bootstrap/js/bootstrap.bundle.min.js'%}"></script>
    <script src="{% static 'assets/vendor/glightbox/js/glightbox.min.js'%}"></script>
    <script src="{% static 'assets/vendor/swiper/swiper-bundle.min.js'%}"></script>
    <script src="{% static 'assets/vendor/php-email-form/validate.js'%}"></script>

    <!-- Template Main JS File -->
    <script src="{% static 'assets/js/main.js'%}"></script>
  <!-- Cropperjs -->
 
    <script type="module" src="{% static 'cropperjs/dist/cropper.min.js' %}"></script>
    <script type="module" src="{% static 'cropperjs/dist/cropper.js' %}"></script>
    <script type="module" src="{% static 'cropperjs/dist/cropper.min.esm.js' %}"></script>
    <script type="module" src="{% static 'cropperjs/dist/cropper.common.js' %}"></script>





</body>

</html>

myvenv2023/GToProject/src/templates/base_old.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
   
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <!--
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
-->
    <!-- bootstrap css -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <!-- style css -->
    <link rel="stylesheet" href="{% static 'css/style.css'%}">
    <!-- Responsive-->
    <link rel="stylesheet" href="{% static  'css/responsive.css'%}">
    <!-- fevicon -->
    <link rel="icon" href="{% static 'images/fevicon.png'%}" type="image/gif" />
    <!-- Scrollbar Custom CSS -->
    <link rel="stylesheet" href="{% static 'css/jquery.mCustomScrollbar.min.css'%}">
    <!-- Tweaks for older IEs-->
    <title>Winner Project</title>

    <style>
        nav {
            background-color: green;
        }
        
        .one-edge-shadow {
            box-shadow: 0 8px 2px -5px rgb(246, 245, 245);
        }
        
        .display-8 {
            font-weight: 200;
            font-size: 30px;
            font-colour: $teal-200;
        }
    </style>
</head>

<body>
    <!-- navbar -->

    <nav class="one-edge-shadow
  navbar navbar-light
  sticky-top navbar 
  navbar-expand-lg
  text-white">
        <a class="navbar-brand ms-3 text-dark " href="/">
            <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">

            <img src="{% static 'images/leptop.jpg'%}" style="width:50px;height:50px,color:text-light;">Trand Economy Project</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>


        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">


            </ul>




            <ul class=" navbar-nav my-2 my-lg-0">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'home'%}">Home <span class="sr-only">(current)</span></a>
                </li>
               

             

                {% if request.session.user %}

               
                <li class="nav-item active ">
                    <a class="nav-link" href="/logout">Logout<span class="sr-only">(current)</span></a>
                </li>
                {% else %}
                 <!--Search start-->
                 <div class="search_area ">
                    <ul class="navbar-nav mx-auto">
                        <li class="nav-item"><i class="search_btn flaticon-magnifier"></i>
                            <div id="search">
                               <!-- <button type="button" class="close">×</button>-->
                               <form action="{% url 'mainapp:search' %}" method="get">
                                <input name="q" type="text" placeholder="Search here...." required/>
                              </form>
                            
                                
                            </div>
                        </li>
                    </ul>
                </div>
                <!--Search end-->
               

                <li class="nav-item active">
                    <a class="nav-link" href="/signupoption">Signup<span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="/login">Login<span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'mainapp:graph' %}">Graph<span class="sr-only">(current)</span></a>
                </li>


               
                {% endif %}


            </ul>


        </div>
    </nav>
    <!---->
    {% block content %}{% endblock %}
    

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <!-- <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>-->

    <!-- Javascript files-->
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.bundle.min.js'%}"></script>
    <script src="{% static 'js/jquery-3.0.0.min.js'%}"></script>
    <!-- sidebar -->
    <script src="{% static 'js/jquery.mCustomScrollbar.concat.min.js'%}"></script>
    <script src="{% static 'js/custom.js'%}"></script>
  
</body>

</html>

myvenv2023/GToProject/src/templates/custome_account_user.html
{% extends 'base.html' %} 
{% block content %}
{% load static%}
<section id="universalbackground" class="universalbackground">

<div class="container mt-4">

    <div class="p-3 m-3">


        <div class="col-lg-5 rounded mx-auto border pt-4">
            <div class="text-center col">

                <img src="{% static 'images/leptop.jpg'%}"
                alt="" class="" style="height: 150px;">
                <!-- <hr> -->
                <hr>
            </div>
            <h1 class="text-center"> Customme Account User</h1>
            <h3 class="alert alert-success rounded-pill" style="text-align:center">Create an Account</h3>
            <form action="/custome_account" method="POST">

                {% csrf_token %} {% if error%}
                <div class="alert alert-danger" role="alert">
                    {{error}}
                </div>
                {% endif %}
               
                <!-- firstname -->
                <div class="form-group text-center mt-3">
                    <label for="">First Name</label>
                    <input type="text" name="firstname" id="" value="{{values.first_name}}" class="form-control form-control-sm" placeholder="">
                </div>

                <!-- last name -->
                <div class="form-group text-center mt-3">
                    <label for="">Last Name</label>
                    <input type="text" name="lastname" id="" value="{{values.last_name}}" class="form-control form-control-sm">
                </div>

                <!-- phone -->
                <div class="form-group text-center mt-3">
                    <label for="">Phone</label>
                    <input type="text" name="phone_number" id="" class="form-control form-control-sm" value="{{values.phone_number}}" placeholder="9876543210">
                </div>
                <!-- email -->
                <div class="form-group text-center mt-3">
                    <label for="">Email</label>
                    <input required type="email" name="email" id="" value="{{values.email}}" class=" form-control-sm form-control" placeholder="abc@gmail.com">
                </div>


                <!-- password -->
                <div class="form-group text-center mt-3">
                    <label for="">Password</label>
                    <input type="password" name="password" id="" class="form-control form-control-sm">
                </div>

                <!--Checkme button-->
                <div class="mb-3 form-check mt-2 ">
                    <input type="checkbox" class="form-check-input" id="exampleCheck1">
                    <label class="form-check-label d-grid gap-2" for="exampleCheck1">Check me out</label>
                </div>
                <hr>
                <button type="submit" class="btn btn-sm btn-success col-lg-12">Create an account</button>

            </form>
        </div>
    </div>
</div>
</section >

{% endblock %}

myvenv2023/GToProject/src/templates/footer.html
<!-- ======= Footer ======= -->
<footer id="footer">
        
    <div class="footer-top">
        <div class="container">
            <div class="row">
            
                <div class="col-lg-6 col-md-6">
                    
                  
                </div>
            
           

                <div class="col-lg-6 col-md-6 footer-links  text-xl-center ">
                    <h4>Useful Links</h4>
                    <ul>
                  
                        
                        <li><i class="bx bx-chevron-right text-center"></i> <a href="{% url 'mainapp:main' %}">Home</a></li>
                        <li><i class="bx bx-chevron-right text-center"></i> <a href="{% url 'mainapp:main' %}">About us</a></li>
                        
                        <li><i class="bx bx-chevron-right text-center"></i> <a href="{% url 'mainapp:news' %}">News</a></li>
                        
                        <li><i class="bx bx-chevron-right text-center"></i> <a href="{% url 'mainapp:privacy'%}">Privacy policy</a></li>
                        <li><i class="bx bx-chevron-right"></i> <a href="{% url 'mainapp:developer'%}">About Developers</a></li>
                      
                   </div> 
                        
                      
                    </ul>
                </div>



                

           </div>
        </div>
    </div>
   

  
</footer>
<!-- End Footer -->

myvenv2023/GToProject/src/templates/footer_old.html
 <!--====== FOOTER PART START ======-->
    
 <footer id="footer-part">
    <div class="footer-top pt-40 pb-70">
        <div class="container">
            <div class="row">
                <div class="col-lg-4 col-md-6">
                    <div class="footer-about mt-40">
                        <div class="logo">
                            <a href="#"><img src="images/logo-2.png" alt="Logo"></a>
                        </div>
                        <p>Gravida nibh vel velit auctor aliquetn quibibendum auci elit cons equat ipsutis sem nibh id elit. Duis sed odio sit amet nibh vulputate.</p>
                        <ul class="mt-20">
                            <li><a href="#"><i class="fa fa-facebook-f"></i></a></li>
                            <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                            <li><a href="#"><i class="fa fa-google-plus"></i></a></li>
                            <li><a href="#"><i class="fa fa-instagram"></i></a></li>
                        </ul>
                    </div> <!-- footer about -->
                </div>
                <div class="col-lg-3 col-md-6 col-sm-6">
                    <div class="footer-link mt-40">
                        <div class="footer-title pb-25">
                            <h6>Sitemap</h6>
                        </div>
                        <ul>
                            <li><a href="index-2.html"><i class="fa fa-angle-right"></i>Home</a></li>
                            <li><a href="about.html"><i class="fa fa-angle-right"></i>About us</a></li>
                            <li><a href="courses.html"><i class="fa fa-angle-right"></i>Courses</a></li>
                            <li><a href="blog.html"><i class="fa fa-angle-right"></i>News</a></li>
                            <li><a href="events.html"><i class="fa fa-angle-right"></i>Event</a></li>
                        </ul>
                        <ul>
                            <li><a href="#"><i class="fa fa-angle-right"></i>Gallery</a></li>
                            <li><a href="shop.html"><i class="fa fa-angle-right"></i>Shop</a></li>
                            <li><a href="teachers.html"><i class="fa fa-angle-right"></i>Teachers</a></li>
                            <li><a href="#"><i class="fa fa-angle-right"></i>Support</a></li>
                            <li><a href="contact.html"><i class="fa fa-angle-right"></i>Contact</a></li>
                        </ul>
                    </div> <!-- footer link -->
                </div>
                <div class="col-lg-2 col-md-6 col-sm-6">
                    <div class="footer-link support mt-40">
                        <div class="footer-title pb-25">
                            <h6>Support</h6>
                        </div>
                        <ul>
                            <li><a href="#"><i class="fa fa-angle-right"></i>FAQS</a></li>
                            <li><a href="#"><i class="fa fa-angle-right"></i>Privacy</a></li>
                            <li><a href="#"><i class="fa fa-angle-right"></i>Policy</a></li>
                            <li><a href="#"><i class="fa fa-angle-right"></i>Support</a></li>
                            <li><a href="#"><i class="fa fa-angle-right"></i>Documentation</a></li>
                        </ul>
                    </div> <!-- support -->
                </div>
                <div class="col-lg-3 col-md-6">
                    <div class="footer-address mt-40">
                        <div class="footer-title pb-25">
                            <h6>Contact Us</h6>
                        </div>
                        <ul>
                            <li>
                                <div class="icon">
                                    <i class="fa fa-home"></i>
                                </div>
                                <div class="cont">
                                    <p>143 castle road 517 district, kiyev port south Canada</p>
                                </div>
                            </li>
                            <li>
                                <div class="icon">
                                    <i class="fa fa-phone"></i>
                                </div>
                                <div class="cont">
                                    <p>+3 123 456 789</p>
                                </div>
                            </li>
                            <li>
                                <div class="icon">
                                    <i class="fa fa-envelope-o"></i>
                                </div>
                                <div class="cont">
                                    <p>info@yourmail.com</p>
                                </div>
                            </li>
                        </ul>
                    </div> <!-- footer address -->
                </div>
            </div> <!-- row -->
        </div> <!-- container -->
    </div> <!-- footer top -->
    
    <div class="footer-copyright pt-10 pb-25">
        <div class="container">
            <div class="row">
                <div class="col-md-8">
                    <div class="copyright text-md-left text-center pt-15">
                        <p><a target="_blank" href="https://www.templateshub.net">Templates Hub</a> </p>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="copyright text-md-right text-center pt-15">
                       
                    </div>
                </div>
            </div> <!-- row -->
        </div> <!-- container -->
    </div> <!-- footer copyright -->
</footer>

<!--====== FOOTER PART ENDS ======-->

myvenv2023/GToProject/src/templates/free_account_user.html
{% extends 'base.html' %} 
{% block content %}
{% load static%}
<section id="universalbackground" class="universalbackground">
<div class="container mt-4">

    <div class="p-3 m-3">


        <div class="col-lg-5 rounded mx-auto border pt-4">
            <div class="text-center col">

                <img src="{% static 'images/leptop.jpg'%}"
                alt="" class="" style="height: 150px;">
                <!-- <hr> -->
                <hr>
            </div>
            <h1 class="text-center"> Free Account User</h1>
            <h3 class="alert alert-success rounded-pill" style="text-align:center">Create an Account</h3>
            <form action="/free_account" method="POST">

                {% csrf_token %} {% if error%}
                <div class="alert alert-danger" role="alert">
                    {{error}}
                </div>
                {% endif %}
               
                <!-- firstname -->
                <div class="form-group text-center mt-3">
                    <label for="">First Name</label>
                    <input type="text" name="firstname" id="" value="{{values.first_name}}" class="form-control form-control-sm" placeholder="">
                </div>

                <!-- last name -->
                <div class="form-group text-center mt-3">
                    <label for="">Last Name</label>
                    <input type="text" name="lastname" id="" value="{{values.last_name}}" class="form-control form-control-sm">
                </div>

                <!-- phone -->
                <div class="form-group text-center mt-3">
                    <label for="">Phone</label>
                    <input type="text" name="phone_number" id="" class="form-control form-control-sm" value="{{values.phone_number}}" placeholder="9876543210">
                </div>
                <!-- email -->
                <div class="form-group text-center mt-3">
                    <label for="">Email</label>
                    <input required type="email" name="email" id="" value="{{values.email}}" class=" form-control-sm form-control" placeholder="abc@gmail.com">
                </div>


                <!-- password -->
                <div class="form-group text-center mt-3">
                    <label for="">Password</label>
                    <input type="password" name="password" id="" class="form-control form-control-sm">
                </div>

                <!--Checkme button-->
                <div class="mb-3 form-check text-center col-3 mt-2">
                    <input type="checkbox" class="form-check-input" id="exampleCheck1">
                    <label class="form-check-label d-grid gap-2" for="exampleCheck1">Check me out</label>
                </div>
                <hr>
                <button type="submit" class="btn btn-sm btn-success col-lg-12">Create an account</button>

            </form>
        </div>
    </div>
</div>
</section>

{% endblock %}

myvenv2023/GToProject/src/templates/search_results.html
{% extends 'base.html' %} 
{% load static%}
{% block content %} 
<section id="universalbackground" class="universalbackground">

<!-- body -->
<div class="container-fluid mt-3">
    <div class="row m-1">


</div>   
</div>   

<!-- body -->
<div class="container-fluid mt-3">
    <div class="row m-1">


        <!-- filter -->

        <div class=" col-lg-12 mx-auto">
            <!-- left side one start-->
            <div class="list-group card-img-top" style="position: relative; height: 350px">

                <p>All Products</p> 
                
                {% if data_list%}

                {% for list in data_list%}
                <p>{{list.key}}</P>
                <p>{{list.doc_count}}</p>
                
                {% endfor%}
                {% else%}
                No Results 
                {% endif%}
            </div>
             <!-- left side one end-->

            


            </div>
        </div>
    </div>
</div>
<div class="container-fluid mt-3 footer" >
<div class="m-0 footerbody">
<p> Footer </p>
  
</div>
</div>
<!--Table data end-->


</section>


{% endblock %}